services:
  - type: web
    name: userneed-classification-app
    region: frankfurt
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python server.py"
    envVars:
      - key: PORT
        value: 8000
